---
title: "Proposal_P8105"
output: github_document
header-includes:
  - \usepackage{titling}
  - \setlength{\droptitle}{-3cm}
  - \pretitle{\begin{center}\Huge\bfseries}
  - \posttitle{\end{center}\vspace{-1.8cm}}
  - \usepackage{setspace}
  - \setstretch{1}
  - \usepackage{titlesec}
  - \titleformat{\section}[block]{\normalfont\Large\bfseries}{\thesection}{1em}{}
  - \titlespacing*{\section}{0pt}{5pt}{5pt}
  - \titlespacing*{\subsection}{0pt}{3pt}{1pt}
geometry: "left=2cm, right=2cm, top=2cm, bottom=2cm"
---

# Intended Title: A Loo-K into New York City’s Parks
—--- Analyzing Sanitation Access and Community Well-being in NYC Parks

Group members: Fengwei Lei (fl2715), Liqi Zhou (lz3014), Maggie Hsu (mh4588), Xueting Li (xl3495), Yining Cao (yc4588)

# 1. Motivation

  From recreation to community gathering, parks play an important role as a public service. Auyeung et al.’s report on New York City’s park usage describe the multifaceted role of parks in supporting community health, such as through providing a common space for socializing and physical activity along with access to nature in an urban setting (Auyeung et al., 2016). Additionally, facilities like drinking fountains provide a convenient and free source of clean water to the public which can prevent dehydration and reduce usage of single-use plastic water bottles. Therefore, we are particularly interested in the role of sanitation infrastructure in public parks such as public bathrooms and drinking fountain availability and maintenance in promoting community health in New York City.  
  This project intends to explore availability of facilities like public bathrooms and water fountains in New York City parks in relation to social and economic factors such as income and parks funding. Additionally, what effect may these facilities bring to public health?

# 2. Intended Final Product

  Our project aims to create a comprehensive, user-friendly website that improves the visibility and accessibility of NYC park data and is designed to support individuals interested in public health, urban  planning, and community resources.  
  The website will present a series of interactive dashboards and visualizations that offer comprehensive insights into NYC parks, covering aspects such as public sanitation, drinking fountains, restroom facilities, and additional data sources, enabling users to intuitively explore and analyze the distribution and condition of parks-wide public amenities. To further enhance interactivity, the platform integrates a Shiny app for real-time data manipulation and in-depth analysis. 
By integrating and presenting these datasets, we aim to empower communities, researchers, and policymakers to make data-informed decisions that enhance public health and urban quality of life.

# 3. Data Source

## 1) [Public Toilet Locations and Availability in NYC Parks (616 * 6)](https://data.cityofnewyork.us/Recreation/Directory-Of-Toilets-In-Public-Parks/hjae-yuav/about_data)
- Contains information on toilet locations, opening years, accessibility, and usage, which helps analyze the distribution of sanitation facilities across parks.

## 2) [Drinking Fountain Locations and Condition (3849 * 13)](https://data.cityofnewyork.us/Recreation/NYC-Parks-Drinking-Fountains/qnv7-p7a2/about_data)
- Details the locations and operational status of drinking fountains, including park names, coordinates, and maintenance data, allowing us to assess their distribution and usability across parks.

## 3) [Public Restroom Conditions & Hazards (56.4k * 22)](https://data.cityofnewyork.us/City-Government/Parks-Inspection-Program-Public-Restroom-Individua/yp6n-7jdy/about_data)
- Provides detailed restroom inspection data, including cleanliness, maintenance status, and safety hazards, allowing us to evaluate the overall state of restrooms and identify improvement areas.

## 4) Additional Data Sources
We may also explore supplementary datasets for a more comprehensive view.

- [Dog Runs](https://data.cityofnewyork.us/Recreation/NYC-Parks-Dog-Runs/8nac-uner): Insights into dog-friendly spaces that may reflect park health.
- [Crime Data](https://data.cityofnewyork.us/Public-Safety/NYC-Park-Crime-Data/ezds-sqp6/about_data): Analysis of park-related crime to understand safety concerns and their impact on amenities.

# 4. Planned Analyses / Visualizations / Coding Challenges
- **Data Fragmentation**: The datasets come from various sources, requiring data consolidation and normalization for consistent analysis.
- **Correlation Complexity**: Identifying relationships between factors is challenging due to the influence of multiple variables.
- **Selecting Appropriate Visualization Types**: Careful selection of visualization methods is necessary for each analysis type to improve readability.
- **Data Cleaning and Integration**: Diverse data formats and missing values across sources demand significant effort for cleaning and merging data for analysis.


# 5. Project Timeline

- **10/28 - 11/8**
  - **Decide project theme, goals, and research questions**: Clarify focus areas for sanitation in public parks.
  - **Complete project proposal**

- **11/11 - 11/15**
  - **Data cleaning and organization**: Prepare datasets for analysis.
  - **Website and report initialization**: Set up the website framework and draft “Motivation,” “Related Work,” “Initial Questions,” and “Data” sections.
  - **Project review meeting**: Discuss project direction and refine tasks based on feedback.

- **11/18 - 11/22**
  - **Exploratory data analysis (EDA)**: Perform EDA on sanitation data and add findings to the website.

- **11/25 - 11/29**
  - **Interactive website development**: Implement interactive features (e.g., Shiny app for toilet locations) and dashboards.

- **12/2 - 12/6**
  - **Report Completion**: Finalize “Additional Analysis” and “Discussion” sections.
  - **Record video**: Summarize project insights for embedding on the website.
  - **Website completion**: Finalize all components.
  - **Peer assessment and feedback**: Gather peer feedback and make final